#!/usr/bin/env python3
# genfont.py - rasterize a libre TTF into anti-aliased glyph coverage
# bitmaps and emit them as a C header (include/font_aa.h). Each glyph is a
# grayscale coverage map (0 = background, 255 = full ink); the kernel's ugfx
# alpha-blends it onto the framebuffer, giving smooth text from the 8x8
# console's blocky look. Run at build time; the output is not committed.
import os
import sys

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:
    sys.exit("genfont: Pillow (python3-pil) is required")

SIZES = [18, 32]  # body, heading
FIRST, LAST = 32, 126
FONT_PATHS = [
    "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    "/usr/share/fonts/dejavu/DejaVuSans.ttf",
    "/usr/share/fonts/TTF/DejaVuSans.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
]


def find_font():
    for p in FONT_PATHS:
        if os.path.exists(p):
            return p
    sys.exit("genfont: no DejaVuSans.ttf found (install fonts-dejavu-core)")


def main():
    path = find_font()
    L = []
    L.append("/* Generated by tools/genfont.py - do not edit. */")
    L.append("#pragma once")
    L.append("#include <stdint.h>")
    L.append("#define AAFONT_FIRST %d" % FIRST)
    L.append("#define AAFONT_LAST %d" % LAST)
    L.append("#define AAFONT_NSIZES %d" % len(SIZES))
    L.append("struct aaglyph { uint8_t w, h, advance; int8_t xoff, yoff; "
             "uint32_t off; };")
    L.append("struct aafont { uint8_t px, height, ascent; "
             "const struct aaglyph *glyphs; const uint8_t *cov; };")

    meta = []
    for si, size in enumerate(SIZES):
        font = ImageFont.truetype(path, size)
        ascent, descent = font.getmetrics()
        height = ascent + descent
        glyphs = []
        cov = []
        off = 0
        for c in range(FIRST, LAST + 1):
            ch = chr(c)
            adv = round(font.getlength(ch))
            box = font.getbbox(ch)
            if not box or box[2] <= box[0] or box[3] <= box[1]:
                glyphs.append((0, 0, adv, 0, 0, off))  # space etc.
                continue
            l, t, r, b = box
            w, h = r - l, b - t
            img = Image.new("L", (w, h), 0)
            ImageDraw.Draw(img).text((-l, -t), ch, fill=255, font=font)
            cov.extend(img.tobytes())  # row-major w*h
            glyphs.append((w, h, adv, l, t - ascent, off))
            off += w * h
        L.append("static const uint8_t aafont_cov%d[] = {%s};" %
                 (si, ",".join(str(x) for x in cov) if cov else "0"))
        L.append("static const struct aaglyph aafont_g%d[] = {%s};" %
                 (si, ",".join("{%d,%d,%d,%d,%d,%d}" % g for g in glyphs)))
        meta.append((size, height, ascent, si))

    L.append("static const struct aafont aafonts[AAFONT_NSIZES] = {%s};" %
             ",".join("{%d,%d,%d,aafont_g%d,aafont_cov%d}" % (m[0], m[1], m[2],
                                                              m[3], m[3])
                      for m in meta))
    sys.stdout.write("\n".join(L) + "\n")
    sys.stderr.write("genfont: %s sizes=%s\n" % (path, SIZES))


main()
